package stats
//import stats.Run.repertoireSourceFichiers

object ConstantesColonnes {

  val COLSSAGESTRANSFORMED: List[String] = List(
    "InitialStartDateTime",
    "id",
    "TicketId",
    "CalledNumber",
    "CallingNumber",
    "CallType",
    "ChargedNumber",
    "transferredto",
    "Motif_appel",
    "SAGES",
    "Type_appel",
    "calledNumber_externe_interne",
    "Origine",
    "Origine_appel_entrant",
    "Appels_emis",
    "Appels_recus",
    "Appels",
    "Mise_en_relation",
    "Appels_SVI",
    "Appels_dissuades",
    "Appels_raccroches",
    "Appels_SVI_non_reconnu",
    "Appels_directs_internes",
    "Appels_directs_externes",
    "Appels_aboutis",
    "Appels_decroches",
    "Appels_non_decroches",
    "Appels_transferes",
    "Appels_renvoyes",
    "Attente_avant_mise_en_relation",
    "Duree_de_navigation",
    "Duree_de_communication",
    "postes_logges",
    "Aboutissement_SVI",
    "Appel_facturable",
    "Appel_vers",
    "Pays"
  )

  val COLSREGLEGESTIONINIT: List[String] = List(
    "InitialStartDateTime",
    "CentralAbbreviatedNumberring",
    "IntegratedServiceVPN",
    "OverflowVPN",
    "ARSService",
    "Disa",
    "BasicCall",
    "OperatorFacility",
    "Substitution",
    "PriorityIncomingCall",
    "Transit",
    "PrivateOverflowToPublic",
    "ReroutingPublicToPrivate",
    "FaxServer",
    "caller",
    "called",
    "temp_caller",
    "started_datetime",
    "bloc_id",
    "CostCenter",
    "InternFacilities",
    "Transfer",
    "TicketId",
    "CalledNumber",
    "CallingNumber",
    "CallType",
    "WaitingDuration",
    "EffectiveCallDuration",
    "ChargedNumber",
    "id",
    "duration",
    "endcause",
    "StartDateTime",
    "transferredto",
    "bloc_name",
    "bloc_duration",
    "Motif_appel",
    "SAGES",
    "CallForwardingUnconditional",
    "CallForwardingOnBusy",
    "CallForwardingOnNoReply",
    "VoiceMail"
  )

  val COLSREGLEGESTIONFINAL: List[String] = List(
    "InitialStartDateTime",
    "TicketId",
    "CalledNumber",
    "CallingNumber",
    "CallType",
    "WaitingDuration",
    "EffectiveCallDuration",
    "StartDateTime",
    "ChargedNumber",
    "id",
    "duration",
    "endcause",
    "transferredto",
    "bloc_name",
    "bloc_duration",
    "Motif_appel",
    "SAGES",
    "CallForwardingUnconditional",
    "CallForwardingOnBusy",
    "CallForwardingOnNoReply",
    "Appel_transfere",
    "VoiceMail",
    "Type_appel",
    "calledNumber_externe_interne",
    "Origine",
    "Origine_appel_entrant",
    "Appels_emis",
    "Appels_recus",
    "Appels",
    "Mise_en_relation",
    "Appels_SVI",
    "Appels_dissuades",
    "Appels_raccroches",
    "Appels_sans_license",
    "Appels_SVI_non_reconnu",
    "Appels_directs_internes",
    "Appels_directs_externes",
    "Appels_aboutis",
    "Appels_decroches",
    "Appels_non_decroches",
    "Appels_transferes",
    "Appels_renvoyes",
    "Attente_avant_mise_en_relation",
    "Duree_de_navigation",
    "Duree_de_communication",
    "postes_logges",
    "Aboutissement_SVI",
    "Horaire_ouverture"
  )
  val COLSFORFAITFINALINTERNATIONAL: List[String] =
    COLSREGLEGESTIONFINAL :+ "len" :+ "Indicatif_numero" :+ "Pays" :+ "Appel_facturable"
  val COLSFORFAITRECUINTERNATIONAL: List[String] = COLSREGLEGESTIONFINAL :+ "len"
  val COLSFORFAITFINAL: List[String]             = COLSREGLEGESTIONFINAL :+ "Appel_facturable" :+ "Appel_vers"

  // TOPAD
  val COLSTOPADWITHOUTDATE: List[String] = List(
    "Code_UA",
    "Code_type_de_structure",
    "Etat",
    "Date_deffet_de_letat",
    "DIR_hierarchique",
    "CI_hierarchique",
    "CB_hierarchique",
    "Libelle_court_1",
    "Libelle_court_2",
    "Libelle_long_2",
    "Libelle_long_1"
  )

  val COLSTOPAD: List[String] = COLSTOPADWITHOUTDATE :+ "Date_limite_de_validite"

  val COLSFINAL: List[String] = List(
    "InitialStartDateTime",
    "CalledNumber",
    "CallingNumber",
    "ChargedNumber",
    "transferredto",
    "Motif_appel",
    "Type_appel",
    "calledNumber_externe_interne as CalledNumber_externe_interne",
    "Origine",
    "Origine_appel_entrant",
    "Appels_emis",
    "Appels_recus",
    "Appels as Appels_reiteres",
    "Mise_en_relation as Mises_en_relation",
    "Appels_SVI",
    "Appels_dissuades",
    "Appels_raccroches",
    "Appels_SVI_non_reconnu",
    "Appels_directs_internes",
    "Appels_directs_externes",
    "Appels_aboutis",
    "Appels_decroches",
    "Appels_non_decroches",
    "Appels_transferes",
    "Appels_renvoyes",
    "Attente_avant_mise_en_relation",
    "Duree_de_navigation as Duree_de_navigation_SVI",
    "Duree_de_communication",
    "postes_logges",
    "Aboutissement_SVI",
    "Appel_facturable",
    "Appel_vers",
    "Pays",
    "SAGES",
    "dayofweek as Day_of_week",
    "Hour",
    "Date",
    "Service",
    "quarter as Quarter_of_hour",
    "Lib_hour"
  )
}
